# Consigne: Complétez les cellules de code puis exécutez-les

### 1. Convertissez un tableau de flottants (32 bits) en un tableau d'entiers (32 bits) sur place

In [11]:
import numpy as np
a = np.array([1.1, 2.9, 3.5], dtype=np.float32)
a = a.astype(np.int32)
print(a)

[1 2 3]


### 2. Quel est l'équivalent de `enumerate` pour les tableaux NumPy ?

In [14]:
a = np.array([[10, 20], [30, 40]])
for index, value in np.ndenumerate(a):
    print(index, value)

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


### 3. Placez aléatoirement 20 éléments dans un tableau t.

In [15]:
t = np.random.rand(20)
print(t)

[0.45862161 0.1988137  0.21072364 0.99433499 0.45804608 0.45320999
 0.07739009 0.12419609 0.41805274 0.99706199 0.36642771 0.34198714
 0.89994572 0.74067141 0.48496813 0.2731219  0.92558219 0.7031061
 0.71400083 0.65822668]


### 4. Soustrayez la moyenne de chaque ligne de t.

In [17]:
import numpy as np
t = np.random.randint(0, 100, size=(5, 5))
t_centered = t - t.mean(axis=1, keepdims=True)
print(t_centered)


[[-17.4 -22.4  32.6  36.6 -29.4]
 [-21.4 -14.4  15.6  25.6  -5.4]
 [ 21.2 -10.8 -26.8  32.2 -15.8]
 [ 54.6   0.6  -1.4 -36.4 -17.4]
 [ 26.4   6.4  26.4 -44.6 -14.6]]


### 5. Creez un tableau t1 de dimension 12\*13 puis triez le par la  10ième colonne.

In [18]:
t1 = np.random.randint(0, 100, size=(12, 13))
t1_sorted = t1[t1[:, 9].argsort()]
print(t1_sorted)

[[14 98 28 46 59 58 20 11 80  2 27 28 75]
 [13 78 84 28 78 73 37 59 68 18 69 19 76]
 [29 51  9 30 37 54  4 74 30 20 77 59 15]
 [92 65 25  5 48 68  0 17 33 23 78 48 77]
 [15 23 54 76 48 60 96 81  4 25 39 87 55]
 [45 71 32 90 79  5  3 29 41 39 89 42 28]
 [58 46 84 24 76 19 88 41 29 51 76 65 86]
 [30 76 35 75 51 15 33 91 12 54 25 79 88]
 [68 18 55 80 72 44  4 62 11 64 75 50  4]
 [30  8 84 26 91 49 47 35 29 81 34 99 28]
 [33 40 54 73 57 19 17 33 93 84 60 70 99]
 [28 72 92 32 64 97 72 57 67 91 94 82 47]]


### 6. Vérifiez si t1 contient des colonnes nulles.


In [19]:
has_null_columns = np.any(np.all(t1 == 0, axis=0))
print("Colonnes nulles :", has_null_columns)

Colonnes nulles : False


### 7. Afficher la diagonal de t1.


In [20]:
diagonal = np.diag(t1)
print(diagonal)

[15 51 84 90 48 58 88 91 93 91 69 50]


### 8. Considérez le vecteur [1, 2, 3, 4, 5], construissez un nouveau vecteur avec 3 zéros consécutifs entre chaque valeur.

In [21]:
v = np.array([1, 2, 3, 4, 5])
v_with_zeros = np.zeros(len(v) * 4 - 3, dtype=int)
v_with_zeros[::4] = v
print(v_with_zeros)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


### 9. Creez un tableau de dimension (5,5,3) puis multipliez le par un tableau de dimension (5,5)

In [22]:
a = np.random.rand(5, 5, 3)
b = np.random.rand(5, 5)
result = a * b[:, :, np.newaxis]
print(result)

[[[0.20925453 0.26944331 0.18092517]
  [0.03205424 0.00393384 0.00895822]
  [0.06837194 0.5083171  0.12592857]
  [0.03361089 0.48456021 0.13992612]
  [0.67682157 0.23549759 0.46328084]]

 [[0.04358278 0.04047601 0.03822936]
  [0.53724466 0.20271505 0.47670255]
  [0.54512934 0.29435855 0.249462  ]
  [0.11670145 0.09812603 0.03513049]
  [0.01908314 0.12992864 0.01549765]]

 [[0.15366872 0.07097781 0.19737275]
  [0.3643615  0.15191442 0.28069077]
  [0.03276815 0.09134371 0.09145598]
  [0.74896226 0.74237716 0.92555116]
  [0.05558743 0.05597491 0.17400391]]

 [[0.03722888 0.4722677  0.0217106 ]
  [0.3127174  0.20471152 0.19496132]
  [0.06979959 0.1035893  0.07651527]
  [0.01719429 0.33780296 0.21143015]
  [0.40981563 0.43345382 0.25711686]]

 [[0.41867676 0.07312556 0.28008526]
  [0.4487515  0.21154598 0.5981827 ]
  [0.06320651 0.26464216 0.09986545]
  [0.01722536 0.02773038 0.01505733]
  [0.98589454 0.34292711 0.68176176]]]


### 10.  Creez un tableau de dimension 12\*5 rempli de nombres impairs puis inverser deux lignes du tableaU

In [23]:
t = np.arange(1, 121, 2).reshape(12, 5)
t[[0, 1]] = t[[1, 0]]  # inverser les lignes 0 et 1
print(t)

[[ 11  13  15  17  19]
 [  1   3   5   7   9]
 [ 21  23  25  27  29]
 [ 31  33  35  37  39]
 [ 41  43  45  47  49]
 [ 51  53  55  57  59]
 [ 61  63  65  67  69]
 [ 71  73  75  77  79]
 [ 81  83  85  87  89]
 [ 91  93  95  97  99]
 [101 103 105 107 109]
 [111 113 115 117 119]]


### 11. Créez un tableau y de dimension 10\*10 contenant des entiers compris entre 1 et 5 puis trouvez la valeur la plus fréquente dans le tableau

In [25]:
y = np.random.randint(1, 6, size=(10, 10))
most_frequent = np.bincount(y.ravel()).argmax()
print("Valeur la plus fréquente :", most_frequent)

Valeur la plus fréquente : 2


### 12. Extrayez tous les blocs contigus de 3x3 contenus dans y

In [26]:
from numpy.lib.stride_tricks import sliding_window_view
blocks = sliding_window_view(y, (3, 3))
print(blocks.shape)  # dimensions des blocs extraits

(8, 8, 3, 3)


### 13.   Afficher les n plus grandes valeurs de y


In [27]:
n = 5
top_n = np.sort(y.ravel())[-n:]
print(top_n)

[5 5 5 5 5]


### 14. Considérez un tableau Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],  générez un tableau R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [28]:
Z = np.arange(1, 15)
R = sliding_window_view(Z, 4)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


### 15. Calculez le rang de z

In [29]:
Z_mat = np.arange(1, 15).reshape(2, 7)
rank = np.linalg.matrix_rank(Z_mat)
print("Rang de Z :", rank)

Rang de Z : 2


### 16. Étant donné un nombre arbitraire de vecteurs, construisez le produit cartésien (toutes les combinaisons de chaque élément).

In [30]:
arrays = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
cartesian = np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))
print(cartesian)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


### 17. Considérez un grand vecteur Z2, calculez Z2 à la puissance 5 en utilisant 3 méthodes différentes.

In [31]:
Z2 = np.arange(1, 6)
method1 = Z2 ** 5
method2 = np.power(Z2, 5)
method3 = np.exp(5 * np.log(Z2))
print(method1, method2, method3)

[   1   32  243 1024 3125] [   1   32  243 1024 3125] [1.000e+00 3.200e+01 2.430e+02 1.024e+03 3.125e+03]


### 18. En considérant une matrice de taille 10x3, extraire les lignes contenant des valeurs différentes (par exemple : [2, 2, 3])

In [32]:
mat = np.random.randint(0, 5, size=(10, 3))
unique_rows = mat[np.any(mat != mat[:, [0]], axis=1)]
print(unique_rows)

[[0 0 1]
 [2 4 4]
 [1 4 2]
 [3 4 1]
 [4 4 1]
 [0 0 2]
 [2 3 3]
 [4 0 3]
 [2 1 2]
 [4 4 3]]


### 19. Créez un tableau de dimension 12 contenant uniquement des 0 et 1 puis afficher les lignes uniques les lignes uniques

In [33]:
bin_array = np.random.randint(0, 2, size=(12, 5))
unique_rows = np.unique(bin_array, axis=0)
print(unique_rows)

[[0 0 0 1 1]
 [0 0 1 1 0]
 [0 1 0 0 0]
 [0 1 0 1 1]
 [0 1 1 1 0]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [1 1 0 0 1]
 [1 1 0 1 0]
 [1 1 1 1 0]]


### 20. Créez deux tableaux de dimension 12*8 et 8*6 puis effectuez leur produit matriciel

In [34]:
A = np.random.randint(0, 10, size=(12, 8))
B = np.random.randint(0, 10, size=(8, 6))
C = A @ B
print(C)

[[ 99 162  96 140 158  76]
 [145 213 110 143 188 153]
 [126 197  92 176 175 148]
 [183 215 142 143 240 168]
 [105 125 111  98 159 113]
 [ 90 118  52  70 124  91]
 [135 163 125 170 208 161]
 [103 157  94 104 165  93]
 [ 98 125  77  90 148  97]
 [158 178 133 215 226 178]
 [115 151 119 162 189 131]
 [104 149  83 145 137  99]]
