# Consigne: Complétez les cellules de code puis exécutez-les

#### 1. Importez le package numpy sous l'alias np

In [16]:
import numpy as np

#### 2. Affichez la version de numpy

In [17]:
print('Version numpy :',np.__version__)

Version numpy : 2.2.3


#### 3. Créez un vecteur nul y de taille 10

In [18]:
y=np.zeros(10)
print('y = ',y)

y =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. Affichez la taille mémoire du vecteur y

In [19]:
print('taille memoire y = ',y.itemsize*y.size)

taille memoire y =  80


#### 6. Créez un vecteur nul y1 de taille 25 sauf la quainzième valeur qui est 15

In [20]:
y1=np.zeros(25)
y1[14]=15
print('y1 = ',y1)

y1 =  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 15.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.]


#### 7. Créez un vecteur z avec des valeurs allant de 2006 à 2025

In [21]:
z=np.arange(2006,2026)
print('z = ',z)

z =  [2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019
 2020 2021 2022 2023 2024 2025]


#### 8. Inversez le  vecteur z

In [22]:
z_inv=z[::-1]
print('z_inv = ',z_inv)

z_inv =  [2025 2024 2023 2022 2021 2020 2019 2018 2017 2016 2015 2014 2013 2012
 2011 2010 2009 2008 2007 2006]


#### 9. Créez une matrice m1 3x3 avec des valeurs pairs comprise entre 5 et 25

In [24]:
m1=np.arange(6, 25, 2)
m2=m1[:9].reshape(3,3)
print('m1 = ',m1)

m1 =  [ 6  8 10 12 14 16 18 20 22 24]


#### 10. Créez une matrix m2 10x10 avec des valeurs aléatoires et trouvez les valeurs minimales et maximales de m2

In [12]:
m2=np.random.random((10,10))
print('m2 = ',m2)

m2 =  [[0.00337681 0.15768149 0.34170737 0.05147449 0.61178052 0.24207384
  0.58526275 0.85818932 0.85951086 0.36817679]
 [0.87983492 0.47379322 0.66205578 0.31461265 0.26614454 0.93100672
  0.72304283 0.80853729 0.16206234 0.97134178]
 [0.03774898 0.91742031 0.04910831 0.85883622 0.39167242 0.86373618
  0.02077023 0.18245164 0.25254799 0.51538563]
 [0.03043034 0.1767124  0.00745639 0.87119632 0.29909942 0.3625143
  0.33921936 0.7149821  0.95345853 0.59169166]
 [0.50316742 0.68186967 0.4754032  0.55882146 0.00683965 0.21949388
  0.4062583  0.80512391 0.72322777 0.43110547]
 [0.72027007 0.47440646 0.07190644 0.27608193 0.0786479  0.02817669
  0.95786675 0.83285172 0.52500442 0.43210788]
 [0.846951   0.5254072  0.41812699 0.84753362 0.59427971 0.15630947
  0.91128526 0.45669027 0.82205901 0.38094691]
 [0.33700161 0.07503904 0.13353293 0.34162421 0.42130688 0.76977889
  0.18818794 0.37072511 0.26452182 0.52251423]
 [0.86113363 0.21127382 0.96107858 0.11612036 0.40457152 0.22415827
  0.701

#### 11. Créez un vecteur aléatoire v1 de taille 30 et trouvez la valeur moyenne.

In [15]:
v1=np.random.random(30)
print('moyenne = ',v1.mean())

moyenne =  0.4525707171491584


### 12. Ajoutez une bordure (remplie de 0) autour d'un tableau existant.

In [45]:
tab=np.ones((3,3))
border=np.pad(tab, pad_width=1, mode='constant', constant_values=0)
print('tab = ',tab)
print('border = ',border)

tab =  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
border =  [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 13. Créez une matrice m3 5x5 avec les valeurs 1, 2, 3, 4 juste en dessous de la diagonale.

In [25]:
m3=np.diag(1+np.arange(4),k=-1)
print('m3 = ',m3)

m3 =  [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 14. Créez une matrice m4 8x8 et remplissez-la avec un motif en damier en utilisant la fonction tile..

In [27]:
m4 = np.zeros((8, 8), dtype=int)
m4[1::2, ::2] = 1
m4[::2, 1::2] = 1
print(m4)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 15. Considérez un tableau de forme (6,7,8), quel est l'indice (x, y, z) du 100e élément ?

In [31]:
print("Indice du 100e:", np.unravel_index(99, (6, 7, 8)))

Indice du 100e: (np.int64(1), np.int64(5), np.int64(3))


#### 16. Normalisez une matrice aléatoire m5 de taille  5x5.

In [32]:
m5 = np.random.rand(5, 5)
m5_normalise = (m5 - m5.min()) / (m5.max() - m5.min())
print(m5_normalise)

[[0.33091328 0.95994855 0.41613365 0.         0.81673498]
 [0.45679696 0.99530508 0.72716429 0.43558517 0.7082858 ]
 [0.23638018 0.1668926  0.63505183 0.74382039 0.29268351]
 [0.37944023 0.76519617 1.         0.40075535 0.64760681]
 [0.14842856 0.0442976  0.67537662 0.25144392 0.84387959]]


#### 17. Multipliez une matrice 5x3 par une matrice 3x2 (produit matriciel réel).

In [26]:
ma1=np.random.random((5,3))
ma2=np.random.random((3,2))
print('ma1*ma2 =  ',np.dot(ma1,ma2))

ma1*ma2 =   [[0.4625017  0.40376548]
 [1.14268371 0.9762965 ]
 [1.27966834 1.09331686]
 [0.99523993 1.08097416]
 [2.02592313 1.53697069]]


#### 16 Comment obtenir toutes les dates correspondant au mois de Mars 2025 ?

In [33]:
dates_march_2025 = np.arange('2025-03', '2025-04', dtype='datetime64[D]')
print(dates_march_2025)

['2025-03-01' '2025-03-02' '2025-03-03' '2025-03-04' '2025-03-05'
 '2025-03-06' '2025-03-07' '2025-03-08' '2025-03-09' '2025-03-10'
 '2025-03-11' '2025-03-12' '2025-03-13' '2025-03-14' '2025-03-15'
 '2025-03-16' '2025-03-17' '2025-03-18' '2025-03-19' '2025-03-20'
 '2025-03-21' '2025-03-22' '2025-03-23' '2025-03-24' '2025-03-25'
 '2025-03-26' '2025-03-27' '2025-03-28' '2025-03-29' '2025-03-30'
 '2025-03-31']


#### 17. Créez un vecteur v2 de taille 10 avec des valeurs allant de 0 à 1, excluant les deux extrémités.

In [34]:
v2 = np.linspace(0, 1, 12, )[1:-1]
print(v2)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


 #### 18. Triez le vecteur V2.

In [44]:
v2_sort = np.sort(v2)
print(v2_sort)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 19. Creer deux tableaux aléatoires A et B, de meme taille, vérifiez s'ils sont égaux ?

In [36]:
A = np.random.random(5)
B = np.random.random(5)
print(np.array_equal(A, B))

False


#### 20. Créez un vecteur v3 aléatoire de taille 10 et remplacez la valeur maximale par 0.

In [ ]:
V3 = np.random.random(10)
V3[V3.argmax()] = 0
print(V3)

#### 21. Creez un tablequ w Affichez toutes les valeurs du tableau.

In [37]:
W=np.random.random((10,2))
print(W)

[[0.37010738 0.34261654]
 [0.70720413 0.72478448]
 [0.4379412  0.00466089]
 [0.73570978 0.55737339]
 [0.84221932 0.20340852]
 [0.03459643 0.0663042 ]
 [0.69546767 0.42855779]
 [0.44869476 0.32897774]
 [0.69619439 0.92133508]
 [0.71119242 0.29675687]]


#### 22. Trouvez la valeur la plus proche 5 dans le vecteur v2.

In [38]:
valeur_cible = 5
plus_proche = v2[np.abs(v2 - valeur_cible).argmin()]
print("Valeur la plus proche de 5 dans v2 :", plus_proche)

Valeur la plus proche de 5 dans v2 : 0.9090909090909092


#### 23. Comment Vérifiez si un tableau 2D donné contient des colonnes nulles.

In [ ]:
arr = np.random.random((3, 3))
print(np.any(np.all(arr== 0, axis = 0)))

[[0.26779231 0.52481272 0.55952278]
 [0.82014418 0.99515421 0.64263669]
 [0.07789181 0.56792815 0.25065881]]
False


### 24. Créez une matrice z de taille 12\*3 remplie uniquement de 1

In [39]:
z = np.ones((12,3))
print(z)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 25. Inversez z

In [40]:
z_inv=z[::-1]
print('z_inv = ',z_inv)

z_inv =  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
